In [1]:
# importing the pandas module for
# data frame
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score




# load the data set into train variable.
train = pd.read_csv('/kaggle/input/vehicle-count/traffic.csv')
train = train.drop('ID', axis=1)

# display top 5 values of data set
train.head()

              DateTime  Junction  Vehicles
0  2015-11-01 00:00:00         1        15
1  2015-11-01 01:00:00         1        13
2  2015-11-01 02:00:00         1        10
3  2015-11-01 03:00:00         1         7
4  2015-11-01 04:00:00         1         9

In [2]:
# function to get all data from time stamp

# get date
def get_dom(dt):
	return dt.day

# get week day
def get_weekday(dt):
	return dt.weekday()

# get hour
def get_hour(dt):
	return dt.hour

# get year
def get_year(dt):
	return dt.year

# get month
def get_month(dt):
	return dt.month

# get year day
def get_dayofyear(dt):
	return dt.dayofyear

# get year week
def get_weekofyear(dt):
	return dt.weekofyear


train['DateTime'] = train['DateTime'].map(pd.to_datetime)
train['date'] = train['DateTime'].map(get_dom)
train['weekday'] = train['DateTime'].map(get_weekday)
train['hour'] = train['DateTime'].map(get_hour)
train['month'] = train['DateTime'].map(get_month)
train['year'] = train['DateTime'].map(get_year)
train['dayofyear'] = train['DateTime'].map(get_dayofyear)
train['weekofyear'] = train['DateTime'].map(get_weekofyear)

# display
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [3]:
train.to_csv('file1.csv')

In [4]:

# display top 5 values of data set
# train = train[train['Junction'] == 1]
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [5]:
# train = train.drop(['Junction'], axis=1)
print(train.columns)

Index(['DateTime', 'Junction', 'Vehicles', 'date', 'weekday', 'hour', 'month',
       'year', 'dayofyear', 'weekofyear'],
      dtype='object')

In [6]:
# there is no use of DateTime module
# so remove it
train = train.drop(['DateTime'], axis=1)

# separating class label for training the data
train1 = train.drop(['Vehicles'], axis=1)

# class label is stored in target
target = train['Vehicles']

print(train1.head())
target.head()

   Junction  date  weekday  hour  month  year  dayofyear  weekofyear
0         1     1        6     0     11  2015        305          44
1         1     1        6     1     11  2015        305          44
2         1     1        6     2     11  2015        305          44
3         1     1        6     3     11  2015        305          44
4         1     1        6     4     11  2015        305          44

0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [7]:
target = pd.read_csv('/kaggle/working/file1.csv')

# separating class label for training the data
train1 = train.drop('Vehicles', axis=1)

# class label is stored in target
target = train['Vehicles']

train1.head()
#target.head()

   Junction  date  weekday  hour  month  year  dayofyear  weekofyear
0         1     1        6     0     11  2015        305          44
1         1     1        6     1     11  2015        305          44
2         1     1        6     2     11  2015        305          44
3         1     1        6     3     11  2015        305          44
4         1     1        6     4     11  2015        305          44

In [ ]:

# train1 = pd.read_csv('/kaggle/working/train1.csv')
# train1 = train1.fillna(train1.mean())
# target = pd.read_csv('/kaggle/working/target.csv')
#importing Random forest
from sklearn.ensemble import RandomForestRegressor

#defining the RandomForestRegressor
m1=RandomForestRegressor()

# m1.fit(train1,target)
#testing
# m1.predict([[11,6,0,1,2015,11,2]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc1=StandardScaler()
scaled_data = sc1.fit_transform(train1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(train1, target, test_size=0.2, random_state=42)

# Create and train the model
# model = DecisionTreeClassifier(random_state=42)
m1.fit(X_train, y_train)
y_pred = m1.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error: {rmse}')
print(f'R-squared: {r2}')

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

# Model Definition
class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, act_layer=nn.GELU, drop=0., pred=True):
        super().__init__()
        hidden_features = hidden_features or in_features
        self.q = nn.Linear(in_features, in_features)
        self.k = nn.Linear(in_features, in_features)
        self.v = nn.Linear(in_features, in_features)
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.pred = pred
        if pred == True:
            self.fc2 = nn.Linear(hidden_features, 1)
        else:
            self.fc2 = nn.Linear(hidden_features, in_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x0 = x
        q = self.q(x).unsqueeze(2)
        k = self.k(x).unsqueeze(2)
        v = self.v(x).unsqueeze(2)
        attn = (q @ k.transpose(-2, -1))
        attn = attn.softmax(dim=-1)
        x = (attn @ v).squeeze(2)
        x += x0
        x1 = x
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        if self.pred == False:
            x += x1
        x = x.squeeze(0)
        return x

class TF(nn.Module):
    def __init__(self, in_features, drop=0.):
        super().__init__()
        self.Block1 = Mlp(in_features=in_features, hidden_features=64, act_layer=nn.GELU, drop=drop, pred=False)
        self.Block2 = Mlp(in_features=in_features, hidden_features=64, act_layer=nn.GELU, drop=drop, pred=True)

    def forward(self, x):
        return self.Block2(self.Block1(x))

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(scaled_data, target, test_size=0.2, random_state=42)

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

# Model Initialization
model = TF(in_features=X_train.shape[1])

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Train the model
def train_model(model, criterion, optimizer, X_train, y_train, epochs=10, batch_size=32):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for i in range(0, len(X_train), batch_size):
            inputs = X_train[i:i+batch_size]
            labels = y_train[i:i+batch_size]

            optimizer.zero_grad()

            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss / len(X_train)}")

train_model(model, criterion, optimizer, X_train_tensor, y_train_tensor)

# Predict on test data
model.eval()
with torch.no_grad():
    predictions = model(X_test_tensor)

# Evaluate model performance
predictions = predictions.squeeze().numpy()
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = mean_squared_error(y_test, predictions, squared=False)
r2 = r2_score(y_test, predictions)

print(f"MAE: {mae}, MSE: {mse}, RMSE: {rmse}, R2 Score: {r2}")

/opt/conda/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 1/10, Loss: 13.963924600794627
Epoch 2/10, Loss: 13.723178999679641
Epoch 3/10, Loss: 13.689702975779698
Epoch 4/10, Loss: 13.673304714962333
Epoch 6/10, Loss: 13.664779045139861
Epoch 7/10, Loss: 13.662553418009656
Epoch 8/10, Loss: 13.662229094422072
Epoch 9/10, Loss: 13.660748833333663
Epoch 10/10, Loss: 13.659610550104333
MAE: 14.494268921743506, MSE: 390.2746856123095, RMSE: 19.75537105731779, R2 Score: 0.042380557774237326