In [9]:
# importing the pandas module for
# data frame
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score




# load the data set into train variable.
train = pd.read_csv('traffic.csv')
train = train.drop('ID', axis=1)

# display top 5 values of data set
train.head()

              DateTime  Junction  Vehicles
0  2015-11-01 00:00:00         1        15
1  2015-11-01 01:00:00         1        13
2  2015-11-01 02:00:00         1        10
3  2015-11-01 03:00:00         1         7
4  2015-11-01 04:00:00         1         9

In [10]:
# function to get all data from time stamp

# get date
def get_dom(dt):
	return dt.day

# get week day
def get_weekday(dt):
	return dt.weekday()

# get hour
def get_hour(dt):
	return dt.hour

# get year
def get_year(dt):
	return dt.year

# get month
def get_month(dt):
	return dt.month

# get year day
def get_dayofyear(dt):
	return dt.dayofyear

# get year week
def get_weekofyear(dt):
	return dt.weekofyear


train['DateTime'] = train['DateTime'].map(pd.to_datetime)
train['date'] = train['DateTime'].map(get_dom)
train['weekday'] = train['DateTime'].map(get_weekday)
train['hour'] = train['DateTime'].map(get_hour)
train['month'] = train['DateTime'].map(get_month)
train['year'] = train['DateTime'].map(get_year)
train['dayofyear'] = train['DateTime'].map(get_dayofyear)
train['weekofyear'] = train['DateTime'].map(get_weekofyear)

# display
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [11]:
train.to_csv('file1.csv')

In [12]:

# display top 5 values of data set
# train = train[train['Junction'] == 1]
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [13]:
# train = train.drop(['Junction'], axis=1)
print(train.columns)

Index(['DateTime', 'Junction', 'Vehicles', 'date', 'weekday', 'hour', 'month',
       'year', 'dayofyear', 'weekofyear'],
      dtype='object')

In [14]:
# there is no use of DateTime module
# so remove it
train = train.drop(['DateTime'], axis=1)

# separating class label for training the data
train1 = train.drop(['Vehicles'], axis=1)

# class label is stored in target
target = train['Vehicles']

print(train1.head())
target.head()

   Junction  date  weekday  hour  month  year  dayofyear  weekofyear
0         1     1        6     0     11  2015        305          44
1         1     1        6     1     11  2015        305          44
2         1     1        6     2     11  2015        305          44
3         1     1        6     3     11  2015        305          44
4         1     1        6     4     11  2015        305          44

0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [15]:
target = pd.read_csv('file1.csv')

# separating class label for training the data
train1 = train.drop('Vehicles', axis=1)

# class label is stored in target
target = train['Vehicles']

train1.head()
#target.head()

   Junction  date  weekday  hour  month  year  dayofyear  weekofyear
0         1     1        6     0     11  2015        305          44
1         1     1        6     1     11  2015        305          44
2         1     1        6     2     11  2015        305          44
3         1     1        6     3     11  2015        305          44
4         1     1        6     4     11  2015        305          44

In [18]:

# train1 = pd.read_csv('/kaggle/working/train1.csv')
# train1 = train1.fillna(train1.mean())
# target = pd.read_csv('/kaggle/working/target.csv')
#importing Random forest
# from sklearn.ensemble import RandomForestRegressor
from keras.models import Sequential
from keras.layers import LSTM, Dense

#defining the RandomForestRegressor
# m1=RandomForestRegressor()
X = train1.values
y = target.values

# m1.fit(train1,target)
#testing
# m1.predict([[11,6,0,1,2015,11,2]])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
model = Sequential()
model.add(LSTM(units=50, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(units=1))


model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1, validation_data=(X_test, y_test))

# Evaluate the model
train_loss = model.evaluate(X_train, y_train, verbose=0)
test_loss = model.evaluate(X_test, y_test, verbose=0)
print(f"Train Loss: {train_loss}")
print(f"Test Loss: {test_loss}")
# Create and train the model
# model = DecisionTreeClassifier(random_state=42)
# m1.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error: {rmse}')
print(f'R-squared: {r2}')

WARNING:tensorflow:From c:\Users\ipl20\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\ipl20\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Epoch 1/50
WARNING:tensorflow:From c:\Users\ipl20\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

1203/1203 [==============================] - 10s 6ms/step - loss: 693.6938 - val_loss: 522.1660
Epoch 2/50
1203/1203 [==============================] - 5s 4ms/step - loss: 497.8875 - val_loss: 424.4006
Epoch 3/50
1203/1203 [==============================] - 6s 5ms/step - loss: 444.1393 - val_loss: 408.1131
Epoch 4/50
1203/1203 [==============================] - 5s 4ms/step - loss: 436.6443 - val_loss: 407.6591
Epoch 5/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2806 - val_loss: 407.8884
Epoch 6/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2907 - val_loss: 407.8875
Epoch 7/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.4135 - val_loss: 407.6675
Epoch 8/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.2979 - val_loss: 407.8344
Epoch 9/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.2884 - val_loss: 407.6336
Epoch 10/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.3090 - val_loss: 407.8139
Epoch 11/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.3153 - val_loss: 407.7709
Epoch 12/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2868 - val_loss: 407.9256
Epoch 13/50
1203/1203 [==============================] - 10s 8ms/step - loss: 436.2888 - val_loss: 407.6934
Epoch 14/50
1203/1203 [==============================] - 11s 9ms/step - loss: 436.2931 - val_loss: 407.8384
Epoch 15/50
1203/1203 [==============================] - 12s 10ms/step - loss: 436.2978 - val_loss: 407.6737
Epoch 16/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2945 - val_loss: 407.7950
Epoch 17/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2962 - val_loss: 407.7206
Epoch 18/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3067 - val_loss: 407.6905
Epoch 19/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2787 - val_loss: 407.9711
Epoch 20/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3025 - val_loss: 407.7400
Epoch 21/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2873 - val_loss: 407.9171
Epoch 22/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3021 - val_loss: 407.7157
Epoch 23/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2844 - val_loss: 407.8882
Epoch 24/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2768 - val_loss: 407.6205
Epoch 25/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2874 - val_loss: 407.6544
Epoch 26/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2975 - val_loss: 407.8440
Epoch 27/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2686 - val_loss: 408.0537
Epoch 28/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3096 - val_loss: 407.6989
Epoch 29/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2941 - val_loss: 407.8327
Epoch 30/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2904 - val_loss: 407.9269
Epoch 31/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2925 - val_loss: 407.7536
Epoch 32/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2951 - val_loss: 407.8038
Epoch 33/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2882 - val_loss: 407.7090
Epoch 34/50
1203/1203 [==============================] - 5s 5ms/step - loss: 436.2932 - val_loss: 407.7832
Epoch 35/50
1203/1203 [==============================] - 9s 7ms/step - loss: 436.3009 - val_loss: 407.7920
Epoch 36/50
1203/1203 [==============================] - 10s 8ms/step - loss: 436.2955 - val_loss: 407.8169
Epoch 37/50
1203/1203 [==============================] - 7s 6ms/step - loss: 436.2953 - val_loss: 407.8185
Epoch 38/50
1203/1203 [==============================] - 5s 5ms/step - loss: 436.2951 - val_loss: 407.7442
Epoch 39/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2877 - val_loss: 407.6607
Epoch 40/50
1203/1203 [==============================] - 7s 6ms/step - loss: 436.2984 - val_loss: 407.8687
Epoch 41/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2974 - val_loss: 407.7440
Epoch 42/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2926 - val_loss: 407.8414
Epoch 43/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2900 - val_loss: 407.7638
Epoch 44/50
1203/1203 [==============================] - 10s 8ms/step - loss: 436.3001 - val_loss: 407.7473
Epoch 45/50
1203/1203 [==============================] - 5s 4ms/step - loss: 436.3044 - val_loss: 407.7684
Epoch 46/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2853 - val_loss: 407.6262
Epoch 47/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3039 - val_loss: 407.7750
Epoch 48/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.2891 - val_loss: 407.7235
Epoch 49/50
1203/1203 [==============================] - 6s 5ms/step - loss: 436.3033 - val_loss: 407.7090
Epoch 50/50
1203/1203 [==============================] - 7s 6ms/step - loss: 436.3044 - val_loss: 407.6988
Train Loss: 436.27093505859375
Test Loss: 407.6987609863281
301/301 [==============================] - 2s 3ms/step
Mean Absolute Error: 15.105370355068597
Mean Squared Error: 407.698861169573
Root Mean Squared Error: 20.1915542039134
R-squared: -0.0003732510007588008