In [1]:
# importing the pandas module for
# data frame
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score




# load the data set into train variable.
train = pd.read_csv('/kaggle/input/vehicle-count/traffic.csv')
train = train.drop('ID', axis=1)

# display top 5 values of data set
train.head()

              DateTime  Junction  Vehicles
0  2015-11-01 00:00:00         1        15
1  2015-11-01 01:00:00         1        13
2  2015-11-01 02:00:00         1        10
3  2015-11-01 03:00:00         1         7
4  2015-11-01 04:00:00         1         9

In [2]:
# function to get all data from time stamp

# get date
def get_dom(dt):
	return dt.day

# get week day
def get_weekday(dt):
	return dt.weekday()

# get hour
def get_hour(dt):
	return dt.hour

# get year
def get_year(dt):
	return dt.year

# get month
def get_month(dt):
	return dt.month

# get year day
def get_dayofyear(dt):
	return dt.dayofyear

# get year week
def get_weekofyear(dt):
	return dt.weekofyear


train['DateTime'] = train['DateTime'].map(pd.to_datetime)
train['date'] = train['DateTime'].map(get_dom)
train['weekday'] = train['DateTime'].map(get_weekday)
train['hour'] = train['DateTime'].map(get_hour)
train['month'] = train['DateTime'].map(get_month)
train['year'] = train['DateTime'].map(get_year)
train['dayofyear'] = train['DateTime'].map(get_dayofyear)
train['weekofyear'] = train['DateTime'].map(get_weekofyear)

# display
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [3]:
train.to_csv('file1.csv')

In [4]:

# display top 5 values of data set
# train = train[train['Junction'] == 1]
train.head()

,DateTime,Junction,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,1,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,1,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,1,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,1,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,1,9,1,6,4,11,2015,305,44

In [5]:
# train = train.drop(['Junction'], axis=1)
print(train.columns)

Index(['DateTime', 'Junction', 'Vehicles', 'date', 'weekday', 'hour', 'month',
       'year', 'dayofyear', 'weekofyear'],
      dtype='object')

In [6]:
# there is no use of DateTime module
# so remove it
train = train.drop(['DateTime'], axis=1)

# separating class label for training the data
# train1 = train.drop(['Vehicles'], axis=1)

# class label is stored in target
train = train['Vehicles']

In [7]:
print(train)

0        15
1        13
2        10
3         7
4         9
         ..
48115    11
48116    30
48117    16
48118    22
48119    12
Name: Vehicles, Length: 48120, dtype: int64

In [8]:
print(train.values)

[15 13 10 ... 16 22 12]

In [13]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, GRU
from sklearn.model_selection import train_test_split
# data_normalized = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
data=train.values
# Define a function to create sequences of past observations
def create_sequences(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i+seq_length])  # Past observations
        y.append(data[i+seq_length])    # Next observation (count of vehicles)
    return np.array(X), np.array(y)

# Define the sequence length (number of past observations to consider)
seq_length = 48  # You want to use the past 7 observations

# Create sequences of past observations
X, y = create_sequences(train.values, seq_length)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

import tensorflow as tf
from tensorflow.keras.layers import MultiHeadAttention, LayerNormalization, Dense, Dropout, Input, GlobalAveragePooling1D

def transformer_encoder(inputs, num_heads, ff_dim, num_layers, dropout_rate):
    x = inputs
    for _ in range(num_layers):
        attn_output = MultiHeadAttention(num_heads=num_heads, key_dim=x.shape[-1])(x, x, return_attention_scores=False)
        attn_output = Dropout(dropout_rate)(attn_output)
        out1 = LayerNormalization(epsilon=1e-6)(x + attn_output)
        ffn_output = Dense(ff_dim, activation='relu')(out1)
        ffn_output = Dense(x.shape[-1])(ffn_output)
        ffn_output = Dropout(dropout_rate)(ffn_output)
        x = LayerNormalization(epsilon=1e-6)(out1 + ffn_output)
    return x

def build_model(input_shape, num_heads, ff_dim, num_layers, dropout_rate):
    inputs = Input(shape=input_shape)
    x = transformer_encoder(inputs, num_heads, ff_dim, num_layers, dropout_rate)
    x = GlobalAveragePooling1D()(x)
    x = Dense(64, activation='relu')(x)
    outputs = Dense(1)(x)
    return tf.keras.models.Model(inputs, outputs)

# Example usage:
input_shape = (seq_length, 1)  # Define input shape according to your data
num_heads = 4          # Number of attention heads
ff_dim = 64            # Dimension of the feed-forward network
num_layers = 2         # Number of transformer layers
dropout_rate = 0.1     # Dropout rate

model = build_model(input_shape, num_heads, ff_dim, num_layers, dropout_rate)
model.compile(optimizer='adam', loss='mae')



# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

# Evaluate the model on the test set
loss = model.evaluate(X_test, y_test)
print("Test Loss:", loss)

# Once trained, you can use this model to predict future observations
# For example, if you have new data X_new with shape (n_samples, seq_length, n_features), you can predict as follows:
# y_pred = model.predict(X_new)

Epoch 1/50
  47/1202 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 25.5586

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1713726591.476193      89 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

1202/1202 ━━━━━━━━━━━━━━━━━━━━ 154s 95ms/step - loss: 24.9904
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 22.6519
Epoch 4/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 21.8603
Epoch 5/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 20.4157
Epoch 6/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 19.6472
Epoch 7/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 18.7280
Epoch 8/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 17.8897
Epoch 9/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 17.2919
Epoch 10/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 16.8466
Epoch 11/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 16.3121
Epoch 12/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 16.0110
Epoch 13/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.9507
Epoch 14/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.6480
Epoch 15/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.5637
Epoch 16/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4299
Epoch 17/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4255
Epoch 18/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 15.5015
Epoch 19/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4296
Epoch 20/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3813
Epoch 21/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4091
Epoch 22/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4586
Epoch 23/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4192
Epoch 24/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3522
Epoch 25/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4138
Epoch 26/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3223
Epoch 27/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3128
Epoch 28/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4484
Epoch 29/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3291
Epoch 30/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3214
Epoch 31/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2144
Epoch 32/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3046
Epoch 33/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.5060
Epoch 34/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 15.3604
Epoch 35/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4531
Epoch 36/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4888
Epoch 37/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3667
Epoch 38/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4400
Epoch 39/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4109
Epoch 40/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4715
Epoch 41/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 15.3109
Epoch 42/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2512
Epoch 43/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4708
Epoch 44/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.3304
Epoch 45/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2041
Epoch 46/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2323
Epoch 47/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4051
Epoch 48/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2797
Epoch 49/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 15.5246
Epoch 50/50
1202/1202 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.5304
301/301 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 7.5363
Test Loss: 8.49406623840332